# Generated by Django 3.1.6 on 2021-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
